version: '3.1'

services:
  mysql:
    image: mysql:8.0.33
    container_name: test-mysql
    restart: always
    environment:
      MYSQL_DATABASE: testDB
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

networks:
  backend:

volumes:
  db_data: