version: '3.1'

services:
  mysql:
    image: mysql:8.0.33
    container_name: test-mysql
    restart: always
    environment:
      MYSQL_DATABASE: testDB
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  redis:
    image: redis:7.0
    container_name: test-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:

volumes:
  db_data: