spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ECOMMERCE
    username: root
    password: noh05love@
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 4000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  level:
    root: INFO
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.hibernate.type.descriptor.sql.BasicBinder: info
    io.hhplus.clean: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
